routes/routes_gis_activity.py
from flask import Blueprint, request, redirect, url_for, flash, jsonify
from models.engine.database import session
from models.gis import Activity
from flask_login import login_required
from models.decorators import required_roles


gis_activity_bp = Blueprint('gis_activity', __name__)


@gis_activity_bp.route("/insert_gis_activity_data", methods=['POST'])
@login_required
@required_roles("admin", "admin_gis")
def insert_gis_activity_data():
    """
    Inserts the GIS data into the database and redirects to the GIS data page.

    Returns:
        flask.Response: A redirect response to the GIS data page or
        a JSON response with an error message.
    """
    if request.method == 'POST':
        try:
            activity = request.form.get('activity_name')
            output_id = request.form.get('output_id')
            responsible_person_id = request.form.get('responsible_person_id')

            new_activity = Activity(
                activity=activity,
                output_id=output_id,
                responsible_person_id=responsible_person_id
            )
            session.add(new_activity)
            session.commit()
            flash('Data inserted successfully!', 'success')
            return redirect(url_for('gis_data.gis_data'))

        except Exception as e:
            session.rollback()
            flash('An error occurred while inserting the data. It looks like the output or responsible person you selected is not valid. Please make sure that the output or responsible person exists before adding the activity.', 'error')
            
            return redirect(url_for('gis_data.gis_data'))
        

        finally:
            session.close()


@gis_activity_bp.route("/update_gis_activity_data/<int:gis_activity_data_id>", methods=['POST'])
@login_required
@required_roles("admin", "admin_gis")
def update_gis_activity_data(gis_activity_data_id):
    """
    Updates the GIS data in the database and redirects to the GIS data page.

    Returns:
        flask.Response: A redirect response to the GIS data page or
        a JSON response with an error message.
    """
    if request.method == 'POST':
        try:
            activity = session.query(Activity).filter_by(id=gis_activity_data_id).first()
            if activity:
                activity.activity = request.form.get('activity_name')
                activity.output_id = request.form.get('output_id')
                activity.responsible_person_id = request.form.get('responsible_person_id')

                session.commit()
                flash('Data updated successfully!', 'success')
            else:
                flash('Activity not found.', 'error')

            return redirect(url_for('gis_data.gis_data'))

        except Exception as e:
            session.rollback()
            flash('An error occurred while updating the data. It looks like the output or responsible person you selected is not valid. Please make sure that the output or responsible person exists before updating the activity.', 'error')
            return redirect(url_for('gis_data.gis_data'))

        finally:
            session.close()


@gis_activity_bp.route("/delete_gis_activity_data/<int:gis_activity_data_id>")
@login_required
@required_roles("admin", "admin_gis")
def delete_gis_activity_data(gis_activity_data_id):
    """
    Deletes the GIS data from the database and redirects to the GIS data page.

    Returns:
        flask.Response: A redirect response to the GIS data page or
        a JSON response with an error message.
    """
    try:
        activity = session.query(Activity).filter_by(id=gis_activity_data_id).first()
        if activity:
            session.delete(activity)
            session.commit()
            flash('Data deleted successfully!', 'success')
        else:
            flash('Activity not found.', 'error')

        return redirect(url_for('gis_data.gis_data'))

    except Exception as e:
        session.rollback()
        flash('An error occurred while deleting the activity. It seems that the activity is associated with an task that cannot be empty. Please check the tasks associated with the Activity.', 'error')

        return redirect(url_for('gis_data.gis_data'))

    finally:
        session.close()

routes/routes_gis_output.py
from flask import Blueprint, request, redirect, url_for, flash, jsonify
from models.engine.database import session
from models.gis import Output
from flask_login import login_required
from models.decorators import required_roles


gis_output_bp = Blueprint('gis_output', __name__)


@gis_output_bp.route("/insert_gis_output_data", methods=['POST'])
@login_required
@required_roles("admin", "admin_gis")
def insert_gis_output_data():
    """
    Inserts the GIS data into the database and redirects to the GIS data page.

    Returns:
        flask.Response: A redirect response to the GIS data page or a
        JSON response with an error message.
    """
    if request.method == 'POST':
        try:
            name = request.form.get('output_name')

            new_output = Output(name=name)
            session.add(new_output)
            session.commit()
            flash('Data inserted successfully!', 'success')
            return redirect(url_for('gis_data.gis_data'))

        except Exception as e:
            session.rollback()
            flash(f'An error occurred while inserting data: {str(e)}', 'error')
            return redirect(url_for('gis_data.gis_data'))

        finally:
            session.close()


@gis_output_bp.route("/update_gis_output_data/<int:gis_output_data_id>", methods=['POST'])
@login_required
@required_roles("admin", "admin_gis")
def update_gis_output_data(gis_output_data_id):
    """
    Updates the GIS data in the database and redirects to the GIS data page.

    Returns:
        flask.Response: A redirect response to the GIS data page or
        a JSON response with an error message.
    """
    if request.method == 'POST':
        try:
            output = session.query(Output).filter_by(id=gis_output_data_id).first()
            if output:
                output.name = request.form.get('output_name')
                session.commit()
                flash('Data updated successfully!', 'success')
            else:
                flash('Output not found.', 'error')
            return redirect(url_for('gis_data.gis_data'))

        except Exception as e:
            session.rollback()
            flash(f'An error occurred while updating data: {str(e)}', 'error')
            return redirect(url_for('gis_data.gis_data'))

        finally:
            session.close()


@gis_output_bp.route("/delete_gis_output_data/<int:gis_output_data_id>")
@login_required
@required_roles("admin", "admin_gis")
def delete_gis_output_data(gis_output_data_id):
    """
    Deletes the GIS data from the database and redirects to the GIS data page.

    Returns:
        flask.Response: A redirect response to the GIS data page or a
        JSON response with an error message.
    """
    try:
        output = session.query(Output).filter_by(id=gis_output_data_id).first()
        if output:
            session.delete(output)
            session.commit()
            flash('Data deleted successfully!', 'success')
        else:
            flash('Output not found.', 'error')
        return redirect(url_for('gis_data.gis_data'))

    except Exception as e:
        session.rollback()
        flash('An error occurred while deleting the output. It seems that the output is associated with an activity that cannot be empty. Please check the activities associated with the output.', 'error')
        return redirect(url_for('gis_data.gis_data'))

    finally:
        session.close()

routes/routes_projects.py
from flask import (
    Blueprint, render_template, abort,
    jsonify, request, redirect, url_for, flash
)
from flask_login import login_required
from models.engine.database import session
from models.plot_functions import today_date
from models.projects import (
    ProjectsData, ProjectManagers
)
from models.decorators import required_roles


projects_bp = Blueprint('projects', __name__)


@projects_bp.route("/projects_data", strict_slashes=False)
@login_required
@required_roles('admin', 'admin_projects')
def projects_data():
    """
    Function to handle projects data retrieval and rendering.

    Retrieves projects data and today's date, then
    renders the projects_data.html template.

    Parameters:
    - None

    Returns:
    - Rendered template "projects_data.html" with today's
    date and projects data.

    """
    projects_data = ProjectsData.projects_data_to_dict_list()
    project_managers = ProjectManagers.project_managers_to_dict_list()
    formatted_date = today_date()
    return render_template("projects_data.html", today_date=formatted_date,
                           projects_data=projects_data,
                           project_managers=project_managers)


@projects_bp.route("/insert_project_manager", methods=['POST'])
@login_required
@required_roles('admin', 'admin_projects', 'admin_struts')
def insert_project_manager():
    """
    Function to handle insert project manager route.
    """
    if request.method == 'POST':
        try:
            name = request.form.get('name')
            section = request.form.get('section')

            new_project_manager = ProjectManagers(name=name, section=section)
            session.add(new_project_manager)
            session.commit()
            flash('Project manager added successfully!', 'success')
            return redirect(request.referrer)

        except Exception as e:
            session.rollback()
            flash(f'An error occurred while adding the project manager: {str(e)}', 'error')
            return redirect(request.referrer)

        finally:
            session.close()


@projects_bp.route(
    "/update_projects_project_manager/<int:project_manager_id>",
    methods=['POST'])
@login_required
@required_roles('admin', 'admin_projects', 'admin_struts')
def update_projects_project_manager(project_manager_id):
    """
    Function to handle update project manager route.
    """
    if request.method == 'POST':
        try:
            project_manager = (
                session.query(ProjectManagers)
                .filter_by(id=project_manager_id)
                .first()
            )
            if project_manager:
                project_manager.name = request.form.get('name')
                project_manager.section = request.form.get('section')
                session.commit()
                flash('Project manager updated successfully!', 'success')
            else:
                flash('Project manager not found.', 'error')

            return redirect(request.referrer)

        except Exception as e:
            session.rollback()
            flash(f'An error occurred while updating the project manager: {str(e)}', 'error')
            return redirect(request.referrer)

        finally:
            session.close()


@projects_bp.route("/delete_projects_project_manager/<int:project_manager_id>")
@login_required
@required_roles('admin', 'admin_projects', 'admin_struts')
def delete_projects_project_manager(project_manager_id):
    """
    Function to handle delete project manager route.

    Parameters:
    - project_manager_id: The ID of the project manager to be deleted.

    Returns:
    - A redirect response to the projects data page.
    """
    try:
        project_manager = (
            session.query(ProjectManagers)
            .filter_by(id=project_manager_id)
            .first()
        )
        if project_manager:
            session.delete(project_manager)
            session.commit()
            flash('Project manager deleted successfully!', 'success')
            return redirect(request.referrer)
        else:
            return redirect(request.referrer)

    except Exception as e:
        session.rollback()
        flash(f'An error occurred while deleting the project manager: {str(e)}', 'error')
        return redirect(request.referrer)
    
    finally:
        session.close()


@projects_bp.route('/insert_projects_data', methods=['POST'])
@login_required
@required_roles('admin', 'admin_projects')
def insert_projects_data():
    """
    Inserts the project data into the database and
    redirects to the projects page.

    Returns:
        flask.Response: A redirect response to the projects
        page or a JSON response with an error message.
    """
    if request.method == 'POST':
        try:
            # Get form data
            contract_number = request.form.get('contract_number')
            contract_name = request.form.get('contract_name')
            contract_type_id = request.form.get('contract_type_id')
            project_manager_id = request.form.get('project_manager_id')
            section_id = request.form.get('section_id')
            contractor = request.form.get('contractor')
            year = request.form.get('year')
            date_contract_signed = request.form.get('date_contract_signed')
            date_contract_signed_by_bcc = (
                request.form.get('date_contract_signed_by_bcc')
                )
            early_start_date = request.form.get('early_start_date')
            contract_duration_weeks = (
                request.form.get('contract_duration_weeks')
                )
            contract_duration_months = (
                request.form.get('contract_duration_months')
                )
            early_finish_date = request.form.get('early_finish_date')
            extension_of_time = request.form.get('extension_of_time')
            project_status = request.form.get('project_status')
            contract_value_including_ten_percent_contingency = (
                request.form
                .get('contract_value_including_ten_percent_contingency')
                )
            performance_guarantee_value = (
                request.form.get('performance_guarantee_value')
            )
            performance_guarantee_expiry_date = (
                request.form.get('performance_guarantee_expiry_date')
            )
            advance_payment_value = request.form.get('advance_payment_value')
            advance_payment_guarantee_expiry_date = (
                request.form.get('advance_payment_guarantee_expiry_date')
            )
            total_certified_interim_payments_to_date = (
                request.form.get('total_certified_interim_payments_to_date')
            )
            financial_progress_percentage = (
                request.form.get('financial_progress_percentage')
            )
            roads_progress = request.form.get('roads_progress')
            water_progress = request.form.get('water_progress')
            sewer_progress = request.form.get('sewer_progress')
            storm_drainage_progress = (
                request.form.get('storm_drainage_progress')
            )
            public_lighting_progress = (
                request.form.get('public_lighting_progress')
            )
            physical_progress_percentage = (
                request.form.get('physical_progress_percentage')
            )
            tax_clearance_validation = (
                request.form.get('tax_clearance_validation')
            )
            link = request.form.get('link')

            # Create new project record
            new_project_record = ProjectsData(
                contract_number=contract_number,
                contract_name=contract_name,
                contract_type_id=contract_type_id,
                project_manager_id=project_manager_id,
                section_id=section_id,
                contractor=contractor,
                year=year,
                date_contract_signed=date_contract_signed,
                date_contract_signed_by_bcc=date_contract_signed_by_bcc,
                early_start_date=early_start_date,
                contract_duration_weeks=contract_duration_weeks,
                contract_duration_months=contract_duration_months,
                early_finish_date=early_finish_date,
                extension_of_time=extension_of_time,
                project_status=project_status,
                contract_value_including_ten_percent_contingency=(
                    contract_value_including_ten_percent_contingency
                ),
                performance_guarantee_value=performance_guarantee_value,
                performance_guarantee_expiry_date=(
                    performance_guarantee_expiry_date
                ),
                advance_payment_value=advance_payment_value,
                advance_payment_guarantee_expiry_date=(
                    advance_payment_guarantee_expiry_date
                ),
                total_certified_interim_payments_to_date=(
                    total_certified_interim_payments_to_date
                ),
                financial_progress_percentage=financial_progress_percentage,
                roads_progress=roads_progress,
                water_progress=water_progress,
                sewer_progress=sewer_progress,
                storm_drainaige_progress=storm_drainage_progress,
                public_lighting_progress=public_lighting_progress,
                physical_progress_percentage=physical_progress_percentage,
                tax_clearance_validation=tax_clearance_validation,
                link=link)

            session.add(new_project_record)
            session.commit()
            flash('Data inserted successfully')
            return redirect(url_for('projects.projects_data'))

        except Exception as e:
            session.rollback()
            return jsonify({'error': str(e)}), 400

        finally:

templates/add_gis_activity_modal.html
{% block content %}
<div id="myGISActivityModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add New Data</h4>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('gis_activity.insert_gis_activity_data') }}" method="post">
                    <div class="form-group">
                        <label>Activity Name <span style="color: red;">*</span></label>
                        <input type="text" class="form-control" name="activity_name" required>
                    </div>
                    <div class="form-group">
                        <label>Output ID <span style="color: red;">*</span></label>
                        <input type="number" class="form-control" name="output_id" required>
                    </div>
                    <div class="form-group">
                        <label>Responsible Person ID <span style="color: red;">*</span></label>
                        <input type="number" class="form-control" name="responsible_person_id" required>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary left-aligned-button" style="float: left;" type="submit">Submit</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/add_gis_modal.html
{% block content %}
<div id="myGISModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add New Data</h4>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('insert_gis_data') }}" method="post">
                    <div class="form-group">
                        <label>Activity<span style="color: red;">*</span></label>
                        <input type="text" class="form-control" name="activity" required>
                    </div>
                    <div class="form-group">
                        <label> Output <span style="color: red;">*</span></label>
                        <select class="form-control" name="output_id" required>
                            <option value="1">Topographical Map Produced</option>
                            <option value="2">Institutionalized GIS Policy</option>
                            <option value="3">Trained staff members</option>
                            <option value="4">Web-based application developed</option>
                            <option value="5">Accurate and up-to-date Geo- databases provided</option>
                            <option value="6">Three (3) decision making tools provided</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label> Responsible Person <span style="color: red;">*</span></label>
                        <select class="form-control" name="responsible_person_id" required>
                            <option value="1">MrS.MkandlaMr P. Ncube/ MrD.Khumalo/Mr N. Mpofu.</option>
                            <option value="2">Mr D. Khumalo/ Mr P. Ncube/ Mr N. Mpofu /Miss S.Ndhlovu.</option>
                            <option value="3">Sibusisiwe Sibanda</option>
                            <option value="4">Bothwell Nhlalo Sibanda</option>
                            <option value="5">Roderick Siziba</option>
                            <option value="6">Sifelani Ngwenya</option>
                            <option value="7">Tumisang Faith Ndlovu</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary left-aligned-button" style="float: left;" type="submit">Submit</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/add_gis_output_modal.html
{% block content %}
<div id="myGISOutputModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add New Data</h4>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('gis_output.insert_gis_output_data') }}" method="post">
                    <div class="form-group">
                        <label>Output Name <span style="color: red;">*</span></label>
                        <input type="text" class="form-control" name="output_name" required>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary left-aligned-button" style="float: left;" type="submit">Submit</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/add_strategic_project_manager_modal.html
{% block content %}
<div id="myStrategicProjectManagerModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add New Data</h4>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('projects.insert_project_manager') }}" method="post">
                    <div class="form-group">
                        <label>Name <span style="color: red;">*</span></label>
                        <input type="text" class="form-control" name="name" required>
                    </div>
                    <div class="form-group">
                        <label>Section</label>
                        <input type="text" class="form-control" name="section" value="Strategic Planning" required readonly>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary left-aligned-button" style="float: left;" type="submit">Submit</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/admin_dashboard.html
{% extends 'index.html'%}

{% block content %}
<div class="admin_dashboard">
    <h1 class="admin-dashboard_title"> Welcome to the Administrator's Dashboard </h1>
    <h3 class="admin-dashboard_select"> Select the data you want to manage</h3>
    <div class="admin_nav_container">
        <a class="admin_nav btn btn-secondary" href="/users_data">Users Data</a>
        <a class="admin_nav btn btn-secondary" href="/strategic_planning_data">Strategic Planning Data</a>
        <a class="admin_nav btn btn-secondary" href="GIS_data">GIS Data</a>
        <a class="admin_nav btn btn-secondary" href="/projects_data">Projects Data</a>
    </div>
</div>
{% endblock%}

templates/footer.html
<footer>
  <ul class="nav justify-content-center">
    <li class="nav-item"><a href="/home" class="nav-link px-2">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Back to Top</a></li>
    <!-- <li class="nav-item"><a href="#" class="nav-link px-2">Admin-Dashboard</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">About</a></li> -->
  </ul>
  <p class="vision text-center">Going Beyond the Obvious in Search of the Unseen</p>
  <div class="contact_info">
    <div class="contact_details">
      <h5>Contact Us</h5>
      <p class="copyright">Address: 3065 Nkulumane 5, Bulawayo</p>
      <p class="copyright">Phone: +263 775 420 334</p>
      <p class="copyright">Email: <a class="email" href="mailto:dylanmlilo12@gmail.com">dylanmlilo12@gmail.com</a></p>
    </div>
    <div class="copyright_date">
      <br><br><br><br><br>
      <p class="copyright">Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved.</p>
    </div>
  </div>
  </footer>

templates/update_gis_output_modal.html
{% block content %}
<!-- Update GIS Output Modal -->
<div class="modal fade" id="updateGISOutputModal{{ output_data.output_id }}" tabindex="-1" role="dialog" aria-labelledby="updateGISOutputModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="updateGISOutputModalLabel">Edit Data</h5>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('gis_output.update_gis_output_data', gis_output_data_id=output_data.output_id) }}" method="post">
            <div class="form-group">
                <label>Output Name <span style="color: red;">*</span></label>
                <input type="text" class="form-control" name="output_name" value="{{ output_data.output_name }}" required>
            </div>
            <div class="form-group">
                <button class="btn btn-primary left-aligned-button" style="float: left;" type="submit">Submit</button>
            </div>
          </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/update_projects_project_manager_modal.html
{% block content %}
<!-- Update Project Manager Modal -->
<div class="modal fade" id="updateProjectsProjectManagerModal{{ project_manager.id }}" tabindex="-1" role="dialog" aria-labelledby="updateProjectsProjectManagerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="updateProjectsProjectManagerModalLabel">Edit Data</h5>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('projects.update_projects_project_manager', project_manager_id=project_manager.id) }}" method="post">
            <div class="form-group">
                <label>Name <span style="color: red;">*</span></label>
                <input type="text" class="form-control" name="name"  value="{{ project_manager.name }}" required>
            </div>
            <div class="form-group">
                <select class="form-control form-select" name="section" required>
                    <option value="Projects">Projects</option>
                    <option value="Water">Water</option>
                    <option value="Sanitation">Sanitation</option>
                    <option value="Electromechanical">Electromechanical</option>
                    <option value="Strategic Planning">Strategic Planning</option>
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-primary left-aligned-button" style="float: left;" type="submit">Submit</button>
            </div>
          </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/update_strategic_project_manager_modal.html
{% block content %}
<!-- Update Strategic Project Manager Modal -->
<div class="modal fade" id="updateStrategicProjectManagerModal{{ project_manager.id }}" tabindex="-1" role="dialog" aria-labelledby="updateStrategicProjectManagerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="updateStrategicProjectManagerModalLabel">Edit Data</h5>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('projects.update_projects_project_manager', project_manager_id=project_manager.id) }}" method="post">
            <div class="form-group">
                <label>Name <span style="color: red;">*</span></label>
                <input type="text" class="form-control" name="name" value="{{ project_manager.name }}" required>
            </div>
            <div class="form-group">
                <label>Section</label>
                <input type="text" class="form-control" name="section" value="Strategic Planning" required readonly>
            </div>
            <div class="form-group">
                <button class="btn btn-primary left-aligned-button" style="float: left;" type="submit">Submit</button>
            </div>
          </form>
      </div>
    </div>
  </div>
{% endblock %}